apiVersion: apps/v1
kind: Deployment
metadata:
  name: organicnow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organicnow-backend
  template:
    metadata:
      labels:
        app: organicnow-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/kkkkhxx/organicnow-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/organicnow
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: organicnow-backend
  ports:
  - port: 8080
    targetPort: 8080
