version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: organicnow-frontend
    ports:
      - "5173:80"  # เปลี่ยนจาก 5173:5173 เป็น 5173:80
    environment:
      - VITE_API_URL=/api  # เปลี่ยนจาก http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy  # รอ backend health check ผ่าน

  backend:
    build: ./backend
    container_name: organicnow-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://organicnow-db:5432/apartment_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  database:
    image: postgres:17-alpine
    container_name: organicnow-db
    restart: always
    environment:
      - POSTGRES_DB=apartment_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
